# Base Python image
FROM python

# Set the working directory
WORKDIR /home/devops/devops_docker/

# Update package list and install curl
RUN apt-get update && apt-get install -y curl

# Install essential Python tools and dependencies
RUN apt install -y python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools

# Install Flask  without cache
RUN pip install --no-cache-dir flask

# Expose the port used by the Flask application
EXPOSE 5000

# Clone the Git repository
RUN git clone https://github.com/Anjalo18/DevOps.git

# Set the default command to run the Python application
CMD ["python", "DevOps/mydevopspro.py"]
